openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts book
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This backend documentation is describing how you can manage your contacts
tags:
  - name: Contacts
    description: Contacts operations.
  - name: Auth
    description: Authorisation.
servers:
  - url: http://localhost:3000
  - url: https://contacts-with-crud.onrender.com
paths:
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: '../swagger/paths/contacts/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{id}/delete.yaml'
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
